name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 4
      id: test-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 4
        setup-command: ''
        command: python3 assignment.py
        input: '120'
        expected-output: '3.13325946491983'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: ''
        command: python3 test.py
        input: '2'
        expected-output: '2.666666666666667'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: ''
        command: python3 assignment.py
        input: '3'
        expected-output: '3.466666666666667'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Test4
      id: test4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test4
        setup-command: ''
        command: python3 assignment.py
        input: '120'
        expected-output: '3.13325946491983'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Test 5
      id: test-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 5
        setup-command: ''
        command: python3 assignment.py
        input: '360'
        expected-output: '3.138814881170333'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Test 6
      id: test-6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 6
        setup-command: ''
        command: python3 assignment.py
        input: '0'
        expected-output: '0'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
        TEST4_RESULTS: "${{steps.test4.outputs.result}}"
        TEST-5_RESULTS: "${{steps.test-5.outputs.result}}"
        TEST-6_RESULTS: "${{steps.test-6.outputs.result}}"
      with:
        runners: test-4,test-2,test-3,test4,test-5,test-6
